global using AutoMapper;
global using FluentValidation;
global using InterviewManagementSystem.Application.CustomClasses;
global using InterviewManagementSystem.Application.CustomClasses.Exceptions;
global using InterviewManagementSystem.Application.CustomClasses.Extensions;
global using InterviewManagementSystem.Application.CustomClasses.Helpers;
global using InterviewManagementSystem.Application.DTOs;
global using InterviewManagementSystem.Domain.CustomClasses;
global using InterviewManagementSystem.Domain.Enums;
global using InterviewManagementSystem.Domain.Interfaces;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using ApplicationException = InterviewManagementSystem.Application.CustomClasses.Exceptions.ApplicationException;
