global using AutoMapper;
global using FluentValidation;
global using InterviewManagementSystem.Application.DTOs;
global using InterviewManagementSystem.Application.Shared;
global using InterviewManagementSystem.Application.Shared.Exceptions;
global using InterviewManagementSystem.Application.Shared.Extensions;
global using InterviewManagementSystem.Application.Shared.Helpers;
global using InterviewManagementSystem.Domain.Entities.MasterData;
global using InterviewManagementSystem.Domain.Enums;
global using InterviewManagementSystem.Domain.Enums.Extensions;
global using InterviewManagementSystem.Domain.Interfaces;
global using InterviewManagementSystem.Domain.Shared.Paginations;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using ApplicationException = InterviewManagementSystem.Application.Shared.Exceptions.ApplicationException;
